#!/usr/bin/env python

# constantvalues.py - This is a LSL2dfg.py output module to generate a raw
# list of constants with their values.
#
# (C) Copyright 2013 Sei Lisa.
# Sei Lisa is the author's username in the Second Life online virtual world.
#
# This file is part of LSL2 Derived Files Generator.
#
#    LSL2 Derived Files Generator is free software: you can redistribute it
#    and/or modify it under the terms of the GNU Lesser General Public License
#    as published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    LSL2 Derived Files Generator is distributed in the hope that it will be
#    useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with LSL2 Derived Files Generator. If not, see
#    <http://www.gnu.org/licenses/>.
#
# Second Life is a trademark of Linden Research, Inc.


import sys

def output(document, defaultdescs, databaseversion, infilename, outfilename, lang, tag):

  version = "0.0.20130101000"

  if outfilename is not None:
    outf = open(outfilename, "w")
  else:
    outf = sys.stdout

  try:

    outf.write('// Generated by LSL2 Derived Files Generator. Database version: %s; output module version: %s\n'
          % (databaseversion, version))

    for element in document:
      if element['cat'] == 'constant':
        name = element['name']
        val = element['value']
        qval = val.replace('\\', '\\\\').replace('\n', '\\n').replace('"', '\\"')

        if element['type'] == 'string':
          outf.write('%s="%s"\n' % (name, qval))
        else:
          outf.write('%s=%s\n' % (name, val))

  finally:
    if outfilename is not None:
      outf.close()

pass
