#!/usr/bin/env python

# kate.py - This is a LSL2dfg.py output module for Kate KDE editor syntax highlighting.
#
# (C) Copyright 2013, 2024 Sei Lisa.
# Sei Lisa is the author's username in the Second Life(R) online virtual world.
#
# This file is part of LSL2 Derived Files Generator.
#
#    LSL2 Derived Files Generator is free software: you can redistribute it
#    and/or modify it under the terms of the GNU Lesser General Public License
#    as published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    LSL2 Derived Files Generator is distributed in the hope that it will be
#    useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with LSL2 Derived Files Generator. If not, see
#    <http://www.gnu.org/licenses/>.
#
# Second Life is a registered trademark of Linden Research, Inc.


import sys

# Python3 does not have this function, so this replaces it with equivalent behavior.
def cmp(a, b):
  return (a > b) - (a < b)

def output(document, defaultdescs, databaseversion, infilename, outfilename, lang, tag):

  version = "0.0.20230603000"

  keywords = []
  types = []
  constants = []
  functions = []
  events = []

  for element in document:
    if element["cat"] == "keyword":
      keywords.append(element["name"])
    elif element["cat"] == "type":
      types.append(element["name"])
    elif element["cat"] == "constant":
      constants.append(element["name"])
    elif element["cat"] == "function":
      functions.append(element["name"])
    elif element["cat"] == "event":
      events.append(element["name"])

  keywords.sort()
  types.sort()
  constants.sort()
  try:
    functions.sort(key=lambda x: x.lower())
  except:
    functions.sort(lambda x,y: cmp(x.lower(), y.lower()))
  events.sort()

  if infilename is not None:
    inf = open(infilename, "r")
  else:
    inf = sys.stdin

  try:
    inputlines = inf.readlines()

  finally:
    if infilename is not None:
      inf.close()

  if outfilename is not None:
    outf = open(outfilename, "w")
  else:
    outf = sys.stdout

  try:

    for line in inputlines:
      if not line.startswith("<<< %s KEYWORDS >>>" % tag):
        outf.write(line)
      else:
        outf.write('<!-- Generated by LSL2 Derived Files Generator. Database version: %s; output module version: %s -->\n'
          % (databaseversion, version))

        outf.write('\t\t<list name="keywords">\n')
        for element in keywords:
          outf.write('\t\t\t<item> ' + element + ' </item>\n')
        outf.write('\t\t</list>\n')

        outf.write('\t\t<list name="types">\n')
        for element in types:
          outf.write('\t\t\t<item> ' + element + ' </item>\n')
        outf.write('\t\t</list>\n')

        outf.write('\t\t<list name="functions">\n')
        for element in functions:
          outf.write('\t\t\t<item> ' + element + ' </item>\n')
        outf.write('\t\t</list>\n')

        outf.write('\t\t<list name="constants">\n')
        for element in constants:
          outf.write('\t\t\t<item> ' + element + ' </item>\n')
        outf.write('\t\t</list>\n')

        outf.write('\t\t<list name="events">\n')
        for element in events:
          outf.write('\t\t\t<item> ' + element + ' </item>\n')
        outf.write('\t\t</list>\n')

  finally:
    if outfilename is not None:
      outf.close()


pass
